<script context="module">
  export async function load({ params, fetch }) {
    const res = await fetch(
      `/firestore/endpoints/projects/${params.project}.json`
    );
    const project = await res.json();

    if (res.ok) {
      return {
        props: {
          project,
        },
      };
    } else {
      console.log("Had an issue fetching projects.");
      return {
        props: {
          projects: "broken",
        },
      };
    }
  }
</script>

<script>
  import Footer from "../../components/structure/Footer.svelte";
  import Gallery from "../../components/Gallery.svelte";
  import Header from "../../components/structure/Header.svelte";
  import TitleDescription from "../../components/TitleDescription.svelte";

  export let project;
</script>

<Header headerLinks={{}} />
<div id="project">
  <div class="curve">
    <div class="block" />
    <!-- generated by https://getwaves.io/ -->
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
      <path
        fill="#e7008a"
        fill-opacity="1"
        d="M0,96L40,101.3C80,107,160,117,240,106.7C320,96,400,64,480,58.7C560,53,640,75,720,112C800,149,880,203,960,229.3C1040,256,1120,256,1200,229.3C1280,203,1360,149,1400,122.7L1440,96L1440,0L1400,0C1360,0,1280,0,1200,0C1120,0,1040,0,960,0C880,0,800,0,720,0C640,0,560,0,480,0C400,0,320,0,240,0C160,0,80,0,40,0L0,0Z"
      />
    </svg>
  </div>

  <div id="featuredMedia">
    {#if project.featured_video}
      <p>Placeholder for Featured Video implementation.</p>
    {:else if project.featured_image}
      <p>BRRRR</p>
    {/if}
  </div>

  <TitleDescription title={project.title}>
    <p slot="p-tag">
      {project.description}
    </p>
  </TitleDescription>
  <Gallery
    gallery_images={project.gallery_images}
    gallery_videos={project.gallery_videos}
  />

  <h1>
    ** NOTE: I'd like to give the ProjectCard the option to go here or directly
    to the project's Live Site.
    <br />I haven't decided on the implementation yet.
    <br />This page will serve as a more in-depth description or presentation of
    a project.
    <br />Ex: A description and gallary for the ML Art project.
  </h1>
</div>
<Footer />

<style>
  #project {
    height: auto;
    min-height: 800px;
    @apply bg-gradient-to-tr from-blue-700 via-blue-800 to-gray-900;
    color: rgb(209, 213, 219);
    position: relative;
    z-index: -2;
    justify-content: center;
  }
  #project .curve {
    position: absolute;
    top: 0;
    left: 0;
    display: block;
    z-index: -1;
    width: 100%;
  }
  .block {
    background-color: #e7008a;
    height: 300px;
  }
</style>
